-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 07:39:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ordenesservicios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ordenesservicios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordenesservicios` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ordenesservicios` ;

-- -----------------------------------------------------
-- Table `ordenesservicios`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenesservicios`.`personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `areaConocimiento` TEXT NOT NULL,
  `edad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ordenesservicios`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenesservicios`.`solicitudes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha` DATE NOT NULL DEFAULT current_timestamp,
  `nombresolicitante` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ordenesservicios`.`tareaservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenesservicios`.`tareaservico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operador` INT NOT NULL,
  `status` CHAR(1) NOT NULL,
  `fecha` DATE NOT NULL,
  `observacion` TEXT NOT NULL,
  `tiempoestimado` TINYINT(20) NOT NULL,
  `solicitud` INT NOT NULL,
  `personal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tareaservico_solicitudes_idx` (`solicitud` ASC) VISIBLE,
  INDEX `fk_tareaservico_personal1_idx` (`personal` ASC) VISIBLE,
  CONSTRAINT `fk_tareaservico_solicitudes`
    FOREIGN KEY (`solicitud`)
    REFERENCES `ordenesservicios`.`solicitudes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareaservico_personal1`
    FOREIGN KEY (`personal`)
    REFERENCES `ordenesservicios`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ordenesservicios`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenesservicios`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(15) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ordenesservicios`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordenesservicios`.`seguimiento` (
  `id` INT NOT NULL,
  `tareas` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT current_timestamp,
  `observaciones` TEXT NOT NULL,
  `tareaservico` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seguimiento_tareaservico1_idx` (`tareaservico` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_tareaservico1`
    FOREIGN KEY (`tareaservico`)
    REFERENCES `ordenesservicios`.`tareaservico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
